export * from './auth.api';
export * from './students.api';
export * from './academic-years.api';
export * from './grades.api';
export * from './tuition.api';
export * from './payments.api';
export * from './reports.api';
export * from './schools.api';
export * from './users.api';
export * as analyticsApi from './analytics.api';
export * as parentApi from './parent.api';
export * as teacherApi from './teacher.api';
export * as studentApi from './student.api';
export * from './subjects.api';
export * from './homework.api';
export * from './announcements.api';
